---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: microservices
  labels:
    app: web
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: ronpal/node-gateway.app
        ports:
          - containerPort: 8080